version: '3'
services:
      app:
        build: .
        ports:
         - '8888:3000'
        links:
         - db
      db:
        image: mysql
        ports:
         - '3308:3308'
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - /var/lib/mysql
        networks:
            - default
      phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db
        ports:
            - 8000:80
        environment:
            PMA_HOST: db
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
